---
title: "Assignment 1"
author: "Xiaoshu Gui"
date: "1/24/2019"
output: pdf_document
---

```{r message=FALSE, warning=FALSE}
# Load packages
library(dplyr)
library(purrr)
library(magrittr)
library(tidyr)
library(tibble)
library(stringr)
library(reshape2)

# Read data
jss <- read.csv("datjss.csv", header=T, sep=",")
sss <- read.csv("datsss.csv", header=T, sep=",")
stu <- read.csv("datstu.csv", header=T, sep=",", na.strings=c(""," ","NA"))
# Note that there are empty cells in stu, we replace them with NAs first.
```

## Exercise 1
* Number of students: 340823
```{r}
summary(stu)
```

* Number of schools: 6165
```{r}
summary(sss)
```

* Number of programs: 33
```{r}
pgm <- stu %>% 
  select(starts_with("choice")) %>% # get a subset of stu (choicepgm1 ~ 6)
  map(., function(x) unique(x)) %>% # find the number of programs in each "choicepgm"
  unlist %>% 
  unique() %>%  # join all the unique programs in 6 choices and find the unique value.
  length() 
```

* Number of choices (school, program): 
```{r}
school <- stu %>%
  select(X:schoolcode6) %>%
  gather(key = 'school', 'schoolcode', -c(X:male)) %>%
  mutate(choice = str_match(school, "[1-6]") %>% as.numeric())

pgm <- stu %>% 
  select(X, choicepgm1:rankplace) %>%
  gather(key = 'program', 'choicepgm', -c(X, jssdistrict, rankplace))   %>%
    mutate(choice = str_match(program, "[1-6]") %>% as.numeric())

stu1 <- left_join(school, pgm, by = c("X", "choice")) %>%
  mutate(choice = paste(stu1$schoolcode, stu1$choicepgm, sep = ","))


  gather(key = 'program', value = 'choicepgm', -c(X:male, jssdistrict:schoolcode)) %>%
# reshape the dataframe by converting school and program choices from wide to long. 
  filter(!is.na(schoolcode) & !is.na(choicepgm))


map(stu1, function(x) c(paste(stu1[x, 4 + stu1$rankplace[[i]]], stu1[x, 10 + stu1$rankplace[[i]]])))

 #  drop_na(., schoolcode1:choicepgm6) # tease out NAs in shool and program choices
stu_c[cbind(seq_along(stu4$rankplace), stu4$rankplace +4))]

#  map(., function(x) gsub("^$|^ $", NA, x)) # replace all empty cells with NAs. 
```

* Missing test score: 179887 (number of NAs in "score" in datstu)

* Apply to the same school (different programs)
```{r}
stu2 <- stu %>%
  select(5:16) %>%
  apply(., 1, function(x) duplicated(x))

a <- stu[2,]
class(a)
duplicated(a)


```

* Apply to less than 6 choices: 20988

```{r}
# rule out NAs in choicepgm, leaving us students who apply 6 choices
stu3 <- drop_na(stu, starts_with("choice"))

# then students who apply less than 6 choices should be total number of students minus those who apply 6 choices:
340823 - count(stu3)

# na.omit(stu[11:16])
```


## Excercise 2
```{r}
# drop students that are not get enrolled in any school-pgm.
stu4 <- stu %>% 
  filter(!is.na(rankplace)) %>% # drop NAs in rankplace
  filter(rankplace < 7) %>%   # drop 99s in rankplace
  mutate(admt = )


apply(stu4, 1, function(x) paste(stu4[,(4 + as.integer(stu4$rankplace[[x]]))], 
                                 stu4[,(10 + as.integer(stu4$rankplace[[x]]))], 
                                 sep = ",", collapse = NULL))





map(t1, function(x) paste(t1[x, 4 + t1$rankplace[[i]]], t1[x, 10 + t1$rankplace[[i]]]))


paste(t1[1,4+5], t1[1,10+5])
paste(t1[2,4+2], t1[2,10+2])
paste(t1[3,4+4], t1[3,10+4])

paste(t1[2, 4+t1$rankplace[[2]]], t1[2, 10+t1$rankplace[[2]]])

stu4$schoolcode

spchoice_1
spchoice_2

admit = spchoice_[i], i = rankplace

t1$rankplace[1]

t1[1,9]
```



## Excercise 3 Distance
```{r}
distance <- stu %>%
  select(X, schoolcode1:schoolcode6, jssdistrict)

dis <- left_join(distance, jss, by)
```

